const { aiConversation } = require('./conversationAgent');
const { createPlan } = require('./trainingPlanService');

// System prompt cho HLV hỏi từng bước và sinh plan khi đủ thông tin
const systemPrompt = `You are a basketball coach. Your job is to help the user build a personalized training plan by asking questions step by step (about their goals, level, injury, etc). When you have enough information, summarize and generate a JSON training plan (3-5 exercises, each with name, description, sets, reps or duration). If you already have enough info, reply ONLY with the JSON array of exercises.`;

async function personalizeChat(userId, { text, audioBase64 }) {
  // Dùng conversation agent với type 'personalize-plan'
  const result = await aiConversation(userId, 'personalize-plan', { text, audioBase64 }, systemPrompt);
  // Nếu reply là JSON array (bắt đầu bằng [), tự động lưu vào DB
  if (result.reply && result.reply.trim().startsWith('[')) {
    let exercises = [];
    try {
      exercises = JSON.parse(result.reply);
    } catch (e) {}
    if (exercises.length > 0) {
      await createPlan(userId, {
        title: 'Personalized Plan',
        description: 'Generated by AI coach',
        exercises
      });
    }
  }
  return result;
}

module.exports = { personalizeChat };
