package com.example.hoopmaster.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Athletic Tech Light design tokens.
private val LightAthleticBackground = Color(0xFFFCF9F8)
private val LightSurfaceLowest = Color(0xFFFFFFFF)
private val LightSurfaceLow = Color(0xFFF6F3F2)
private val LightSurface = Color(0xFFF0EDEC)
private val LightSurfaceHigh = Color(0xFFEBE7E7)
private val LightSurfaceHighest = Color(0xFFE5E2E1)
private val LightSurfaceDim = Color(0xFFDCD9D9)
private val LightSurfaceBright = Color(0xFFFCF9F8)
private val LightPrimary = Color(0xFFB02F00)
private val LightOnPrimary = Color(0xFFFFFFFF)
private val LightPrimaryContainer = Color(0xFFFF5722)
private val LightOnPrimaryContainer = Color(0xFF541200)
private val LightSecondary = Color(0xFF1B6D24)
private val LightOnSecondary = Color(0xFFFFFFFF)
private val LightSecondaryContainer = Color(0xFFA0F399)
private val LightOnSecondaryContainer = Color(0xFF217128)
private val LightTertiary = Color(0xFF006096)
private val LightOnTertiary = Color(0xFFFFFFFF)
private val LightTertiaryContainer = Color(0xFF007ABC)
private val LightOnTertiaryContainer = Color(0xFFFDFCFF)
private val LightOnSurface = Color(0xFF1C1B1B)
private val LightOnSurfaceVariant = Color(0xFF5B4039)
private val LightInverseSurface = Color(0xFF313030)
private val LightInverseOnSurface = Color(0xFFF3F0EF)
private val LightOutline = Color(0xFF907067)
private val LightOutlineVariant = Color(0xFFE4BEB4)
private val LightSurfaceVariant = Color(0xFFE5E2E1)
private val LightError = Color(0xFFBA1A1A)
private val LightOnError = Color(0xFFFFFFFF)
private val LightErrorContainer = Color(0xFFFFDAD6)
private val LightOnErrorContainer = Color(0xFF93000A)

var AthleticBackground = LightAthleticBackground
var SurfaceLowest = LightSurfaceLowest
var SurfaceLow = LightSurfaceLow
var Surface = LightSurface
var SurfaceHigh = LightSurfaceHigh
var SurfaceHighest = LightSurfaceHighest
var SurfaceDim = LightSurfaceDim
var SurfaceBright = LightSurfaceBright
var Primary = LightPrimary
var OnPrimary = LightOnPrimary
var PrimaryContainer = LightPrimaryContainer
var OnPrimaryContainer = LightOnPrimaryContainer
var Secondary = LightSecondary
var OnSecondary = LightOnSecondary
var SecondaryContainer = LightSecondaryContainer
var OnSecondaryContainer = LightOnSecondaryContainer
var Tertiary = LightTertiary
var OnTertiary = LightOnTertiary
var TertiaryContainer = LightTertiaryContainer
var OnTertiaryContainer = LightOnTertiaryContainer
var OnSurface = LightOnSurface
var OnSurfaceVariant = LightOnSurfaceVariant
var InverseSurface = LightInverseSurface
var InverseOnSurface = LightInverseOnSurface
var Outline = LightOutline
var OutlineVariant = LightOutlineVariant
var SurfaceVariant = LightSurfaceVariant
var SurfaceTint = Primary
val Transparent = Color.Transparent

var Success = Secondary
var OnSuccess = OnSecondary
var SuccessContainer = SecondaryContainer
var ActiveOrange = PrimaryContainer
var NavyShadow = OnSurface
var Error = LightError
var OnError = LightOnError
var ErrorContainer = LightErrorContainer
var OnErrorContainer = LightOnErrorContainer

// Athletic Tech dark design tokens.
val DarkAthleticBackground = Color(0xFF1E100C)
val DarkSurfaceLowest = Color(0xFF180B07)
val DarkSurfaceLow = Color(0xFF271813)
val DarkSurface = Color(0xFF2C1C17)
val DarkSurfaceHigh = Color(0xFF372621)
val DarkSurfaceHighest = Color(0xFF43302B)
val DarkSurfaceDim = Color(0xFF1E100C)
val DarkSurfaceBright = Color(0xFF483530)
val DarkPrimary = Color(0xFFFFB5A0)
val DarkOnPrimary = Color(0xFF5F1500)
val DarkPrimaryContainer = Color(0xFFFF5722)
val DarkOnPrimaryContainer = Color(0xFF541200)
val DarkSecondary = Color(0xFF78DC77)
val DarkOnSecondary = Color(0xFF00390A)
val DarkSecondaryContainer = Color(0xFF00761F)
val DarkOnSecondaryContainer = Color(0xFF95FB92)
val DarkTertiary = Color(0xFF86CFFF)
val DarkOnTertiary = Color(0xFF00344C)
val DarkTertiaryContainer = Color(0xFF019AD8)
val DarkOnTertiaryContainer = Color(0xFF002D43)
val DarkOnSurface = Color(0xFFFADCD4)
val DarkOnSurfaceVariant = Color(0xFFE4BEB4)
val DarkInverseSurface = Color(0xFFFADCD4)
val DarkInverseOnSurface = Color(0xFF3E2C27)
val DarkOutline = Color(0xFFAB8980)
val DarkOutlineVariant = Color(0xFF5B4039)
val DarkSurfaceVariant = Color(0xFF43302B)
val DarkSurfaceTint = DarkPrimary
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)

val HoopMasterLightColorScheme: ColorScheme = lightColorScheme(
    primary = LightPrimary,
    onPrimary = LightOnPrimary,
    primaryContainer = LightPrimaryContainer,
    onPrimaryContainer = LightOnPrimaryContainer,
    inversePrimary = Color(0xFFFFB5A0),
    secondary = LightSecondary,
    onSecondary = LightOnSecondary,
    secondaryContainer = LightSecondaryContainer,
    onSecondaryContainer = LightOnSecondaryContainer,
    tertiary = LightTertiary,
    onTertiary = LightOnTertiary,
    tertiaryContainer = LightTertiaryContainer,
    onTertiaryContainer = LightOnTertiaryContainer,
    error = LightError,
    onError = LightOnError,
    errorContainer = LightErrorContainer,
    onErrorContainer = LightOnErrorContainer,
    background = LightAthleticBackground,
    onBackground = LightOnSurface,
    surface = LightSurfaceLowest,
    onSurface = LightOnSurface,
    surfaceVariant = LightSurfaceVariant,
    onSurfaceVariant = LightOnSurfaceVariant,
    outline = LightOutline,
    outlineVariant = LightOutlineVariant,
    inverseSurface = LightInverseSurface,
    inverseOnSurface = LightInverseOnSurface,
    surfaceTint = LightPrimary
)

val HoopMasterDarkColorScheme: ColorScheme = darkColorScheme(
    primary = DarkPrimary,
    onPrimary = DarkOnPrimary,
    primaryContainer = DarkPrimaryContainer,
    onPrimaryContainer = DarkOnPrimaryContainer,
    inversePrimary = LightPrimary,
    secondary = DarkSecondary,
    onSecondary = DarkOnSecondary,
    secondaryContainer = DarkSecondaryContainer,
    onSecondaryContainer = DarkOnSecondaryContainer,
    tertiary = DarkTertiary,
    onTertiary = DarkOnTertiary,
    tertiaryContainer = DarkTertiaryContainer,
    onTertiaryContainer = DarkOnTertiaryContainer,
    error = DarkError,
    onError = DarkOnError,
    errorContainer = DarkErrorContainer,
    onErrorContainer = DarkOnErrorContainer,
    background = DarkAthleticBackground,
    onBackground = DarkOnSurface,
    surface = DarkSurfaceLowest,
    onSurface = DarkOnSurface,
    surfaceVariant = DarkSurfaceVariant,
    onSurfaceVariant = DarkOnSurfaceVariant,
    outline = DarkOutline,
    outlineVariant = DarkOutlineVariant,
    inverseSurface = DarkInverseSurface,
    inverseOnSurface = DarkInverseOnSurface,
    surfaceTint = DarkSurfaceTint
)

val HoopMasterColorScheme: ColorScheme = HoopMasterLightColorScheme

fun applyHoopThemeTokens(darkTheme: Boolean) {
    AthleticBackground = if (darkTheme) DarkAthleticBackground else LightAthleticBackground
    SurfaceLowest = if (darkTheme) DarkSurfaceLowest else LightSurfaceLowest
    SurfaceLow = if (darkTheme) DarkSurfaceLow else LightSurfaceLow
    Surface = if (darkTheme) DarkSurface else LightSurface
    SurfaceHigh = if (darkTheme) DarkSurfaceHigh else LightSurfaceHigh
    SurfaceHighest = if (darkTheme) DarkSurfaceHighest else LightSurfaceHighest
    SurfaceDim = if (darkTheme) DarkSurfaceDim else LightSurfaceDim
    SurfaceBright = if (darkTheme) DarkSurfaceBright else LightSurfaceBright
    Primary = if (darkTheme) DarkPrimary else LightPrimary
    OnPrimary = if (darkTheme) DarkOnPrimary else LightOnPrimary
    PrimaryContainer = if (darkTheme) DarkPrimaryContainer else LightPrimaryContainer
    OnPrimaryContainer = if (darkTheme) DarkOnPrimaryContainer else LightOnPrimaryContainer
    Secondary = if (darkTheme) DarkSecondary else LightSecondary
    OnSecondary = if (darkTheme) DarkOnSecondary else LightOnSecondary
    SecondaryContainer = if (darkTheme) DarkSecondaryContainer else LightSecondaryContainer
    OnSecondaryContainer = if (darkTheme) DarkOnSecondaryContainer else LightOnSecondaryContainer
    Tertiary = if (darkTheme) DarkTertiary else LightTertiary
    OnTertiary = if (darkTheme) DarkOnTertiary else LightOnTertiary
    TertiaryContainer = if (darkTheme) DarkTertiaryContainer else LightTertiaryContainer
    OnTertiaryContainer = if (darkTheme) DarkOnTertiaryContainer else LightOnTertiaryContainer
    OnSurface = if (darkTheme) DarkOnSurface else LightOnSurface
    OnSurfaceVariant = if (darkTheme) DarkOnSurfaceVariant else LightOnSurfaceVariant
    InverseSurface = if (darkTheme) DarkInverseSurface else LightInverseSurface
    InverseOnSurface = if (darkTheme) DarkInverseOnSurface else LightInverseOnSurface
    Outline = if (darkTheme) DarkOutline else LightOutline
    OutlineVariant = if (darkTheme) DarkOutlineVariant else LightOutlineVariant
    SurfaceVariant = if (darkTheme) DarkSurfaceVariant else LightSurfaceVariant
    SurfaceTint = Primary
    Success = Secondary
    OnSuccess = OnSecondary
    SuccessContainer = SecondaryContainer
    ActiveOrange = PrimaryContainer
    NavyShadow = OnSurface
    Error = if (darkTheme) DarkError else LightError
    OnError = if (darkTheme) DarkOnError else LightOnError
    ErrorContainer = if (darkTheme) DarkErrorContainer else LightErrorContainer
    OnErrorContainer = if (darkTheme) DarkOnErrorContainer else LightOnErrorContainer
}
